# Generated by Django 2.2.11 on 2020-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='access',
            field=models.IntegerField(default=1),
        ),
    ]
